# Generated by Django 4.1.5 on 2023-02-02 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='escudo',
            field=models.ImageField(null=True, upload_to='escudos'),
        ),
    ]
