# Generated by Django 4.1.5 on 2023-02-02 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_equipo_escudo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipo',
            old_name='escudo',
            new_name='imagen',
        ),
    ]
