# Generated by Django 4.1.5 on 2023-02-03 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_escudo_equipo_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_jugador', models.CharField(max_length=200)),
                ('foto', models.ImageField(null=True, upload_to='jugadores')),
                ('fecha_nacimiento', models.DateField()),
                ('dorsal', models.IntegerField()),
                ('goles', models.IntegerField()),
                ('asistencias', models.IntegerField()),
                ('amarillas', models.IntegerField()),
                ('rojas', models.IntegerField()),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.equipo')),
            ],
        ),
    ]
