# Generated by Django 4.1.5 on 2023-02-03 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_jugador'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Jugador',
        ),
    ]
