# Generated by Django 4.1.5 on 2023-02-03 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_jugador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tabla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos', models.IntegerField()),
                ('goles_favor', models.IntegerField()),
                ('goles_contra', models.IntegerField()),
                ('partidos_ganados', models.IntegerField()),
                ('partidos_perdidos', models.IntegerField()),
                ('partidos_empatados', models.IntegerField()),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.equipo')),
            ],
        ),
    ]
