# Generated by Django 4.1.5 on 2023-02-03 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_tabla'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabla',
            name='partidos_jugados',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
