# Generated by Django 4.1.5 on 2023-02-04 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_tabla_partidos_jugados'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabla',
            name='diferencia',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tabla',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.equipo'),
        ),
    ]
