# Generated by Django 4.1.5 on 2023-02-10 01:26

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_equipo_id_alter_jugador_id_alter_tabla_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='imagen',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='escudos'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jugador',
            name='foto',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='jugadores'),
            preserve_default=False,
        ),
    ]
