# Generated by Django 4.1.5 on 2023-02-10 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_equipo_imagen_alter_jugador_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='imagen',
            field=models.ImageField(null=True, upload_to='escudos'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='foto',
            field=models.ImageField(null=True, upload_to='jugadores'),
        ),
    ]
