# Generated by Django 4.1.5 on 2023-02-13 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_equipo_imagen_alter_jugador_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='pagina',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
